jobs:
- name: git-resource-job
  plan:
  - get: git-repo
    trigger: true
  - task: list-resources
    file: git-repo/list-resources/task.yml

resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/Taysburgh/My-Awesome-Repository.git
    branch: master
